"""
AD BRIEF — brand-level image style + OPTIONAL human overrides.
==============================================================
IMPORTANT: the image prompt and the copy are normally GENERATED by the Art
Director / Copywriter agents from the audience + product data (see
generation_pipeline.py). You do NOT hand-write the subject here.

This file holds two things:
  1) Brand-level imagery STYLE the AI applies to every prompt (look & feel, the
     things that should be constant for the brand).
  2) Optional MANUAL OVERRIDES — leave them empty ("") to let the AI generate;
     fill one in to force a specific prompt/headline (mirrors the manual-copy
     mode in the ad-spec). This is the human-in-the-loop escape hatch.
"""

# ── Brand-level imagery style (constant look the AI applies) ────────────────
BRAND_IMAGE_STYLE = "warm natural light, shallow depth of field, the product as hero, inviting and human, rich on-brand tones"
NEGATIVE_PROMPT   = "text, words, logos, watermark, extra fingers, misshapen cup, deformed lid"
PHOTO_TAG         = "high-end advertising photography, no text, no logos, ultra detailed"

# ── Optional human overrides (empty = let the AI generate from data) ────────
MANUAL_IMAGE_PROMPT = ""     # e.g. "a single PSL on a rainy windowsill, moody"
MANUAL_HEADLINE     = ""     # e.g. "Fall, in a cup."
MANUAL_SUBHEAD      = ""     # e.g. "Back for the season."
